// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification_token.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE FROM email_verification_tokens WHERE token = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, token)
	return err
}

const deleteEmailVerificationTokensByUserID = `-- name: DeleteEmailVerificationTokensByUserID :exec
DELETE FROM email_verification_tokens WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationTokensByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensByUserID, userID)
	return err
}

const getEmailVerificationTokenByToken = `-- name: GetEmailVerificationTokenByToken :one
SELECT id, user_id, token, expires_at, created_at FROM email_verification_tokens WHERE token = $1
`

func (q *Queries) GetEmailVerificationTokenByToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
