// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"
)

const getSystemStats = `-- name: GetSystemStats :one
SELECT
    (SELECT count(*) FROM users WHERE deleted_at IS NULL) AS active_users,
    (SELECT count(*) FROM users WHERE deleted_at IS NOT NULL) AS deleted_users,
    (SELECT count(*) FROM files WHERE deleted_at IS NULL) AS total_files,
    (SELECT COALESCE(SUM(size), 0)::BIGINT FROM files WHERE deleted_at IS NULL) AS total_file_size
`

type GetSystemStatsRow struct {
	ActiveUsers   int64 `json:"active_users"`
	DeletedUsers  int64 `json:"deleted_users"`
	TotalFiles    int64 `json:"total_files"`
	TotalFileSize int64 `json:"total_file_size"`
}

func (q *Queries) GetSystemStats(ctx context.Context) (GetSystemStatsRow, error) {
	row := q.db.QueryRow(ctx, getSystemStats)
	var i GetSystemStatsRow
	err := row.Scan(
		&i.ActiveUsers,
		&i.DeletedUsers,
		&i.TotalFiles,
		&i.TotalFileSize,
	)
	return i, err
}
